//
//  FriendsStorage.swift
//  VkontakteApp028
//
//  Created by PiZero on 15.08.2021.
//

import UIKit

class FriendsStorage {
    
    let myFriends: [FriendsModel]
    let allFiends: [FriendsModel]
    
    init() {
        myFriends = [FriendsModel(imageFriends: "wo_6", nameFriends: "Джеймс Хоулетт", photo: [PhotoModel(photoName: "wo_1", likeCount: 35, theLike: false),PhotoModel(photoName: "wo_2", likeCount: 6, theLike: false), PhotoModel(photoName: "wo_3", likeCount: 63, theLike: false), PhotoModel(photoName: "wo_4", likeCount: 23, theLike: false), PhotoModel(photoName: "wo_5", likeCount: 15, theLike: false), PhotoModel(photoName: "wo_6", likeCount: 19, theLike: false), PhotoModel(photoName: "wo_7", likeCount: 48, theLike: false), PhotoModel(photoName: "wo_8", likeCount: 3, theLike: false), PhotoModel(photoName: "wo_9", likeCount: 4, theLike: false), PhotoModel(photoName: "wo_10", likeCount: 1, theLike: false), PhotoModel(photoName: "wo_11", likeCount: 42, theLike: false)]),
                     FriendsModel(imageFriends: "sp_6", nameFriends: "Питер Паркер", photo: [PhotoModel(photoName: "sp_1",likeCount: 57, theLike: false), PhotoModel(photoName: "sp_2", likeCount: 69, theLike: false), PhotoModel(photoName: "sp_3", likeCount: 72, theLike: false), PhotoModel(photoName: "sp_4", likeCount: 80, theLike: false), PhotoModel(photoName: "sp_5", likeCount: 53, theLike: false), PhotoModel(photoName: "sp_6", likeCount: 79, theLike: false), PhotoModel(photoName: "sp_7", likeCount: 55, theLike: false)])
        ]
        
        allFiends = [FriendsModel(imageFriends: "ca_6", nameFriends: "Стивен Роджерс", photo: [PhotoModel(photoName: "ca_1", likeCount: 21, theLike: false), PhotoModel(photoName: "ca_2", likeCount: 7, theLike: false), PhotoModel(photoName: "ca_3", likeCount: 61, theLike: false), PhotoModel(photoName: "ca_4", likeCount: 22, theLike: false), PhotoModel(photoName: "ca_5", likeCount: 79, theLike: false), PhotoModel(photoName: "ca_6", likeCount: 52, theLike: false)]),
                     FriendsModel(imageFriends: "mg_4", nameFriends: "Эрик Леншер", photo: [PhotoModel(photoName: "mg_1", likeCount: 100, theLike: false), PhotoModel(photoName: "mg_2", likeCount: 93, theLike: false), PhotoModel(photoName: "mg_3", likeCount: 87, theLike: false), PhotoModel(photoName: "mg_4", likeCount: 96, theLike: false), PhotoModel(photoName: "mg_5",likeCount: 99, theLike: false)]),
                     FriendsModel(imageFriends: "ve_3", nameFriends: "Venom", photo: [PhotoModel(photoName: "ve_1", likeCount: 61, theLike: false), PhotoModel(photoName: "ve_2", likeCount: 77, theLike: false), PhotoModel(photoName: "ve_3", likeCount: 58, theLike: false), PhotoModel(photoName: "ve_4", likeCount: 67, theLike: false), PhotoModel(photoName: "ve_5", likeCount: 73, theLike: false), PhotoModel(photoName: "ve_6", likeCount: 34, theLike: false), PhotoModel(photoName: "ve_8", likeCount: 50, theLike: false), PhotoModel(photoName: "ve_9", likeCount: 68, theLike: false), PhotoModel(photoName: "ve_10", likeCount: 22, theLike: false)]),
                     FriendsModel(imageFriends: "cr_3", nameFriends: "Carnage", photo: [PhotoModel(photoName: "cr_1", likeCount: 39, theLike: false), PhotoModel(photoName: "cr_2", likeCount: 78, theLike: false), PhotoModel(photoName: "cr_3", likeCount: 99, theLike: false), PhotoModel(photoName: "cr_4", likeCount: 60, theLike: false), PhotoModel(photoName: "cr_5", likeCount: 87, theLike: false), PhotoModel(photoName: "cr_6", likeCount: 59, theLike: false), PhotoModel(photoName: "cr_7", likeCount: 109, theLike: false)]),
                     FriendsModel(imageFriends: "pr_8", nameFriends: "Predator", photo: [PhotoModel(photoName: "pr_1", likeCount: 78, theLike: false), PhotoModel(photoName: "pr_2", likeCount: 100, theLike: false), PhotoModel(photoName: "pr_3", likeCount: 77, theLike: false), PhotoModel(photoName: "pr_4", likeCount: 83, theLike: false), PhotoModel(photoName: "pr_5", likeCount: 71, theLike: false), PhotoModel(photoName: "pr_6", likeCount: 126, theLike: false), PhotoModel(photoName: "pr_7", likeCount: 60, theLike: false), PhotoModel(photoName: "pr_8", likeCount: 59, theLike: false), PhotoModel(photoName: "pr_9", likeCount: 98, theLike: false)]),
                     FriendsModel(imageFriends: "sc_3", nameFriends: "Scorpion", photo: [PhotoModel(photoName: "sc_1", likeCount: 236, theLike: false), PhotoModel(photoName: "sc_2", likeCount: 137, theLike: false), PhotoModel(photoName: "sc_3", likeCount: 100, theLike: false), PhotoModel(photoName: "sc_4", likeCount: 299, theLike: false), PhotoModel(photoName: "sc_5", likeCount: 350, theLike: false), PhotoModel(photoName: "sc_6", likeCount: 245, theLike: false), PhotoModel(photoName: "sc_7", likeCount: 66, theLike: false), PhotoModel(photoName: "sc_8", likeCount: 155, theLike: false), PhotoModel(photoName: "sc_9", likeCount: 99, theLike: false), PhotoModel(photoName: "sc_10", likeCount: 177, theLike: false), PhotoModel(photoName: "sc_11", likeCount: 222, theLike: false), PhotoModel(photoName: "sc_12", likeCount: 36, theLike: false), PhotoModel(photoName: "sc_13", likeCount: 101, theLike: false)]),
                     FriendsModel(imageFriends: "sub_3", nameFriends: "Sub-Zero", photo: [PhotoModel(photoName: "sub_1", likeCount: 99, theLike: false), PhotoModel(photoName: "sub_2", likeCount: 189, theLike: false), PhotoModel(photoName: "sub_3", likeCount: 233, theLike: false), PhotoModel(photoName: "sub_4", likeCount: 200, theLike: false), PhotoModel(photoName: "sub_5", likeCount: 301, theLike: false), PhotoModel(photoName: "sub_6", likeCount: 177, theLike: false), PhotoModel(photoName: "sub_7", likeCount: 101, theLike: false), PhotoModel(photoName: "sub_8", likeCount: 288, theLike: false), PhotoModel(photoName: "sub_9", likeCount: 336, theLike: false), PhotoModel(photoName: "sub_10", likeCount: 155, theLike: false)]), FriendsModel(imageFriends: "noob_5", nameFriends: "Noob Saibot", photo: [PhotoModel(photoName: "noob_4", likeCount: 40, theLike: false),PhotoModel(photoName: "noob_3", likeCount: 99, theLike: false), PhotoModel(photoName: "noob_2", likeCount: 144, theLike: false), PhotoModel(photoName: "noob_1", likeCount: 172, theLike: false), PhotoModel(photoName: "noob_6", likeCount: 199, theLike: false), PhotoModel(photoName: "noob_5", likeCount: 101, theLike: false)]), FriendsModel(imageFriends: "baraka_1", nameFriends: "Baraka", photo: [PhotoModel(photoName: "baraka_6", likeCount: 45, theLike: false),PhotoModel(photoName: "baraka_3", likeCount: 78, theLike: false), PhotoModel(photoName: "baraka_2", likeCount: 99, theLike: false), PhotoModel(photoName: "baraka_1", likeCount: 167, theLike: false), PhotoModel(photoName: "baraka_4", likeCount: 122, theLike: false), PhotoModel(photoName: "baraka_5", likeCount: 201, theLike: false)])
        ]
    }
}
